### ISSUE TITLE
Is the app still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [ClassicDIY/ClassicMonitor#29]
Hi @graham22, I just wonder if the app is still maintained, with no commit for a year and the newest issue comments even older. If so, could you please tell what commit the APK at the latest release was built from? I've tried to rebuild it from the commit the tag points to, to see if it is a [Reproducible Build](https://reproducible-builds.org/), but the resulting APK shows quite some differences:

```diff
-------------------------------
--- /dev/fd/63  2024-07-13 00:54:45.785710131 +0200
+++ /dev/fd/62  2024-07-13 00:54:45.785710131 +0200
@@ -1,17 +1,17 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         3c557a5b
   classes.dex
-  32-bit CRC value (hex):                         9cffe696
+  32-bit CRC value (hex):                         f0482074
   assets/about-de.html
-  32-bit CRC value (hex):                         f10a7837
+  32-bit CRC value (hex):                         a9cd06a1
   assets/about-es.html
-  32-bit CRC value (hex):                         f1d6f2cd
+  32-bit CRC value (hex):                         02195079
   assets/about-fr.html
-  32-bit CRC value (hex):                         b62f880f
+  32-bit CRC value (hex):                         94aeef89
   assets/about-it.html
-  32-bit CRC value (hex):                         da8eb9d7
+  32-bit CRC value (hex):                         580a7670
   assets/about.html
-  32-bit CRC value (hex):                         c6240576
+  32-bit CRC value (hex):                         a767e5a9
   META-INF/android.arch.core_runtime.version
   32-bit CRC value (hex):                         5cd9fe4c
   META-INF/android.arch.lifecycle_livedata-core.version
@@ -863,7 +863,7 @@
   org/joda/time/tz/data/ZoneInfoMap
   32-bit CRC value (hex):                         bc1b8cdd
   AndroidManifest.xml
-  32-bit CRC value (hex):                         c66f3c9a
+  32-bit CRC value (hex):                         e1ec5a9b
   res/-9.png
   32-bit CRC value (hex):                         32e1fa8f
   res/-B.png
```

Taking a closer look at the differences in the `AndroidManifest.xml`:

```diff
-    A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=273
-    A: http://schemas.android.com/apk/res/android:versionName(0x0101021c)="2.7.3" (Raw: "2.7.3")
+    A: http://schemas.android.com/apk/res/android:versionCode(0x0101021b)=274
+    A: http://schemas.android.com/apk/res/android:versionName(0x0101021c)="2.7.4" (Raw: "2.7.4")
```

So your APK must have been built from an older commit.

**Comment by graham22** [comment]
Just published version 2.7.5 that targets SDK 34, pending google review...

**Comment by IzzySoft** [comment]
> Just published version 2.7.5

Where? Releases page still has 2.7.4 as the latest one. Tags only has 2.7.4 as the latest one. I can only test if the release is there with the APK attached – and we don't care about what Google says :stuck_out_tongue_winking_eye:

**Comment by IzzySoft** [comment]
Ah, now it's there – but build fails. Your gradle wrapper seems not the one you use, it still points to gradle-7.5 while your build needs at least gradle-8.7:

```
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 8.7.
```

So I've "injected" gralde-8.9 into the build recipe. Build succeeds then, but again it is **NOT** reproducible:

```diff
--- /dev/fd/63  2024-08-08 02:17:55.236876924 +0200
+++ /dev/fd/62  2024-08-08 02:17:55.236876924 +0200
@@ -1,19 +1,19 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         b337ed0c
   META-INF/version-control-info.textproto
-  32-bit CRC value (hex):                         2cccc6e8
+  32-bit CRC value (hex):                         55a25e6d
   classes.dex
   32-bit CRC value (hex):                         ac44bc7d
   assets/about-de.html
-  32-bit CRC value (hex):                         b0c91fb5
+  32-bit CRC value (hex):                         1c05f77c
   assets/about-es.html
-  32-bit CRC value (hex):                         dfe34b83
+  32-bit CRC value (hex):                         adc73e9f
   assets/about-fr.html
-  32-bit CRC value (hex):                         8366426b
+  32-bit CRC value (hex):                         6b8af931
   assets/about-it.html
-  32-bit CRC value (hex):                         e3e30303
+  32-bit CRC value (hex):                         580a7670
   assets/about.html
-  32-bit CRC value (hex):                         66120a4f
+  32-bit CRC value (hex):                         f4bbfbdd
   META-INF/android.arch.core_runtime.version
   32-bit CRC value (hex):                         5cd9fe4c
   META-INF/android.arch.lifecycle_livedata-core.version
```

This APK was not built from the commit the tag points to (7a28953670a66153aabcca439b602180a2ddf27f), but from 8947a8aade6dda0e1320fbe4055ee6908c9399b6 (as noted in `META-INF/version-control-info.textproto`). We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) you might wish to look at for further hints; the first and basic rule is to always build from a clean tree of the commit the tag points to :wink:

Building from the mentioned commit shows an even larger diff (the resulting APK is ~100 kB larger than the one attached to releases), so there seems to be more wrong.

Can you please reopen this issue and help us establishing Reproducible Builds here, @graham22?

**Comment by obfusk** [comment]
@IzzySoft actually, if that diff you posted is complete I think it is reproducible. Just needs a soft reset for the commit hash and fix-newlines for `assets/*.html ` (the crc32s for `about.html` match the tag, one version CRLF the other LF).

**Comment by IzzySoft** [comment]
Indeed it does, Fay – thanks! Apologies, I'm a little beside me these days it seems.

@graham22 with future releases, please remember to build the APK **after** you've committed all changes, see §1 in the [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) :wink: Thanks!
